[colors.bright]
black = "#323641"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#c8ccd4"
yellow = "#e5c07b"

[colors.cursor]
cursor = "#abb2bf"
text = "#1f2329"

[colors.normal]
black = "#1f2329"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#000000"
bright_foreground = "#c8ccd4"
foreground = "#abb2bf"

[colors.selection]
background = "#30363f"
text = "#abb2bf"

[font]
size = 11

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Regular"

[mouse]
hide_when_typing = true

[window]
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
